<?php

declare(strict_types=1);

/*
 * MessagesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MessagesLib\Models;

use stdClass;

class CheckDeliveryReportsResponse implements \JsonSerializable
{
    /**
     * @var array[]
     */
    private $deliveryReports;

    /**
     * @param array[] $deliveryReports
     */
    public function __construct(array $deliveryReports)
    {
        $this->deliveryReports = $deliveryReports;
    }

    /**
     * Returns Delivery Reports.
     *
     * @return array[]
     */
    public function getDeliveryReports(): array
    {
        return $this->deliveryReports;
    }

    /**
     * Sets Delivery Reports.
     *
     * @required
     * @maps delivery_reports
     *
     * @param array[] $deliveryReports
     */
    public function setDeliveryReports(array $deliveryReports): void
    {
        $this->deliveryReports = $deliveryReports;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['delivery_reports'] = $this->deliveryReports;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
