<?php

declare(strict_types=1);

/*
 * MessagesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MessagesLib\Models;

use stdClass;

class CheckRepliesResponse implements \JsonSerializable
{
    /**
     * @var array[]
     */
    private $replies;

    /**
     * @param array[] $replies
     */
    public function __construct(array $replies)
    {
        $this->replies = $replies;
    }

    /**
     * Returns Replies.
     *
     * @return array[]
     */
    public function getReplies(): array
    {
        return $this->replies;
    }

    /**
     * Sets Replies.
     *
     * @required
     * @maps replies
     *
     * @param array[] $replies
     */
    public function setReplies(array $replies): void
    {
        $this->replies = $replies;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['replies'] = $this->replies;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
