<?php

declare(strict_types=1);

/*
 * MessagesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MessagesLib\Models;

use stdClass;

class ConfirmRepliesAsReceivedRequest implements \JsonSerializable
{
    /**
     * @var string[]
     */
    private $replyIds;

    /**
     * @param string[] $replyIds
     */
    public function __construct(array $replyIds)
    {
        $this->replyIds = $replyIds;
    }

    /**
     * Returns Reply Ids.
     *
     * @return string[]
     */
    public function getReplyIds(): array
    {
        return $this->replyIds;
    }

    /**
     * Sets Reply Ids.
     *
     * @required
     * @maps reply_ids
     *
     * @param string[] $replyIds
     */
    public function setReplyIds(array $replyIds): void
    {
        $this->replyIds = $replyIds;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['reply_ids'] = $this->replyIds;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
