<?php

declare(strict_types=1);

/*
 * MessagesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MessagesLib\Models;

use stdClass;

class ConfirmDeliveryReportsAsReceivedRequest implements \JsonSerializable
{
    /**
     * @var string[]
     */
    private $deliveryReportIds;

    /**
     * @param string[] $deliveryReportIds
     */
    public function __construct(array $deliveryReportIds)
    {
        $this->deliveryReportIds = $deliveryReportIds;
    }

    /**
     * Returns Delivery Report Ids.
     *
     * @return string[]
     */
    public function getDeliveryReportIds(): array
    {
        return $this->deliveryReportIds;
    }

    /**
     * Sets Delivery Report Ids.
     *
     * @required
     * @maps delivery_report_ids
     *
     * @param string[] $deliveryReportIds
     */
    public function setDeliveryReportIds(array $deliveryReportIds): void
    {
        $this->deliveryReportIds = $deliveryReportIds;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['delivery_report_ids'] = $this->deliveryReportIds;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
