<?php

declare(strict_types=1);

/*
 * MessagesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MessagesLib\Models;

use stdClass;

class SendMessagesResponse implements \JsonSerializable
{
    /**
     * @var array[]
     */
    private $messages;

    /**
     * @param array[] $messages
     */
    public function __construct(array $messages)
    {
        $this->messages = $messages;
    }

    /**
     * Returns Messages.
     *
     * @return array[]
     */
    public function getMessages(): array
    {
        return $this->messages;
    }

    /**
     * Sets Messages.
     *
     * @required
     * @maps messages
     *
     * @param array[] $messages
     */
    public function setMessages(array $messages): void
    {
        $this->messages = $messages;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['messages'] = $this->messages;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
